spring.application.name=ms-evidence

# service discovery
# service directory
# Ex.: Eureka

server.port=8083

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=30MB
spring.servlet.multipart.max-request-size=30MB